<%@ include file="/common/sirius-general-top.jsp"%>
<div class="toolbar">
	<a class="item-button-back" href="<c:url value='/page/productionorderdetailbarcodepreadd.htm?id=${barcode_add.productionOrderDetail.id}'/>"><span><spring:message code="sirius.back"/></span></a>
	<a class="item-button-save" ><span><spring:message code="sirius.save"/></span></a>
</div>
<div class="main-box">
	<sesform:form id="addForm" name="addForm" method="post" modelAttribute="barcode_add" enctype="multipart/form-data">
	    <table width="100%" border="0">
			<tr>
				<td width="60%">
					<table style="border:none" width="100%">
						<tr>
							<td width="34%" align="right"><spring:message code="sirius.id"/></td>
							<td width="1%" align="center">:</td>
							<td width="64%"><input class="inputbox input-disabled" value="Auto Number" disabled/></td>
							<td width="1%"><form:errors path="code"/></td>
						</tr>
						<tr>
							<td align="right"><spring:message code="sirius.date"/></td>
							<td width="1%" align="center">:</td>
							<td><input id="date" name="date" class="datepicker" value="<fmt:formatDate value='${barcode_add.date}' pattern='dd-MM-yyyy'/>"/></td>
						</tr>
						<tr>
							<td align="right"><spring:message code="productionorderdetail"/></td>
							<td width="1%" align="center">:</td>
							<td>
								<select id="productionOrderDetail" name="productionOrderDetail" class="combobox-ext">
									<option value="${barcode_add.productionOrderDetail.id}" label="${barcode_add.productionOrderDetail.code}"/>
								</select>
							</td>
						</tr>
						<tr>
							<td align="right"><spring:message code="barcoding.output"/></td>
							<td width="1%" align="center">:</td>
							<td>
								<select id="product" name="product" class="combobox-ext">
									<option value="${barcode_add.product.id}" label="${barcode_add.product.code}"/>
								</select>
							</td>
						</tr>
						<tr>
							<td align="right"><spring:message code="barcoding.conemark"/></td>
							<td width="1%" align="center">:</td>
							<td><form:input id="coneMark" path="coneMark" cssClass="input-disabled" readonly="true"/></td>
						</tr>
						<tr>
							<td align="right"><spring:message code="barcoding.qty"/></td>
							<td width="1%" align="center">:</td>
							<td><form:input id="quantity" path="quantity" cssClass="number-disabled" readonly="true"/></td>
						</tr>
						<tr>
							<td align="right">PIC</td>
							<td width="1%" align="center">:</td>
							<td><form:input id="pic" path="pic" cssClass="input-disabled" readonly="true"/></td>
						</tr>
						<tr>
							<td align="right"><spring:message code="sirius.note"/></td>
							<td width="1%" align="center">:</td>
							<td><form:textarea path="productionOrder.note" rows="6" cols="45"/></td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</td>
				<td width="40%" valign="top">
				</td>
	    	</tr>
	    </table>
    	<br/>
    	<div id="mainTab" dojoType="TabContainer" style="width:100% ; height: 400px;">
			<div id="productLineItem" dojoType="ContentPane" label="<spring:message code='salesorder.lineitem'/>" class="tab-pages" refreshOnShow="true" selected="true">
				<div class="toolbar-clean">
					<table class="table-list" id="lineItemTable" cellspacing="0" cellpadding="0" align="center"  style="width:100%;">
						<thead>
							<tr>
								<th width="1%"></th>
								<th width="10%" nowrap="nowrap"><spring:message code="barcode"/></th>
								<th width="5%" nowrap="nowrap">No</th>
								<th width="8%" nowrap="nowrap"><spring:message code="barcoding.lotno"/></th>
								<th width="12%" nowrap="nowrap"><spring:message code="productionorder.threadtype"/></th>
								<th width="12%" nowrap="nowrap"><spring:message code="barcoding.conemark"/></th>
								<th width="10%" nowrap="nowrap"><spring:message code="barcoding.coneqty"/></th>
								<th width="10%" nowrap="nowrap"><spring:message code="barcoding.bruto"/></th>
								<th width="10%" nowrap="nowrap"><spring:message code="barcoding.netto"/></th>
								<th width="5%" nowrap="nowrap"><spring:message code="sirius.uom"/></th>
							</tr>
						</thead>
						<tbody id="lineItem">
							<c:forEach begin="1" end="${barcode_add.quantity}" varStatus="status">
								<tr>
									<td>&nbsp;</td>
									<td><input value="Autogenerated" class="input-disabled" disabled/></td>
									<td><input value="Auto" class="input-disabled" size="4" disabled/></td>
									<td><input id="lotCode[${status.index}]" name="items[${status.index}].lotCode" class="input-disabled inputbox" value="${barcode_add.productionOrderDetail.productionOrder.lotNumber}" readonly/></td>
									<td>
										<select id="product[${status.index}]" name="items[${status.index}].product" class="input-disabled combobox" readonly>
											<option value="${barcode_add.product.id}" label="${barcode_add.product.name}">
										</select>
									</td>
									<td><input id="coneMark[${status.index}]" name="items[${status.index}].coneMark" class="input-disabled inputbox-min" value="${barcode_add.coneMark}" readonly/></td>
									<td><input id="quantityCone[${status.index}]" name="items[${status.index}].quantityCone" class="input-decimal" value="0.00" size="12"/></td>
									<td><input id="quantity[${status.index}]" name="items[${status.index}].quantity" class="input-decimal" value="0.00" size="12"/></td>
									<td><input id="quantityReal[${status.index}]" name="items[${status.index}].quantityReal" class="input-decimal" value="0.00" size="12"/></td>
									<td><input class="input-disabled" value="${barcode_add.product.unitOfMeasure.measureId}" size="8" disabled/></td>
								</tr>
							</c:forEach>
						</tbody>
						<tfoot>
							<tr class="end-table"><td colspan="10">&nbsp;</td></tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</sesform:form>
</div>
<%@ include file="/common/sirius-general-bottom.jsp"%>
<script type="text/javascript">
	$(function(){
		$('.item-button-save').click(function() {
			if (validation())
				save();
        });
	});
	
	function validation()
	{
		return true;
	}
	
	function save() {
		$.ajax({
		    url:"<c:url value='/page/productionorderdetailbarcodeadd.htm'/>",
		    data:$('#addForm').serialize(),
		    type : 'POST',
		    dataType : 'json',
		    beforeSend:function()
		    {
		      $dialog.empty();
		      $dialog.html('<spring:message code="notif.saving"/>');
		      $dialog.dialog('open');
		    },
		    success : function(json) {
		    	if(json)
		    	{
		        	if(json.status === 'OK')
		        	{
		          		$dialog.dialog('close');
		          		window.location="<c:url value='/page/productionorderdetailbarcodepreedit.htm?id='/>"+json.id;
		        	}
		        	else
		        	{
		          		$dialog.empty();
		          		$dialog.html('<spring:message code="notif.profailed"/> :<br/>'+json.message);
		        	}
				}
			}
		});
	}
</script>