/**
 * Jan 3, 2008 3:15:46 PM
 * com.siriuserp.sdk.utility
 * TableType.java
 */
package com.siriuserp.sdk.dm;

/**
 * @author Agung Dodi Perdana
 * Sirius Indonesia, PT
 * www.siriuserp.com
 */
public enum TableType
{
	//A
	ASSEMBLE_PLAN("ASP"),
	ANDROID_SLIDER("ADS"),
	AUTOMATIC_ENTRY("AE"),
	ANDROID_UPDATE_APK("AUA"),
	ANDROID_SETTING_TIMER("AST"),
	ASSEMBLE_REALIZATION("ASR"),
	
	//B
	BUDGET("BU"),
	BARCODE_PRODUCT(""),
	BARCODE_MOVING(""),
	BILLING("IN"),
	BUNDLE_ORDER("BDO"),
	BILL_OF_MATERIAL("BOM"),
    BANK_TRANSACTION_INCOME("BTI"),
    BANK_TRANSACTION_EXPENSE("BTE"),
    BARCODE_GROUP("BAR"),
    BANK_ACCOUNT("BA"),
	
	//C
	CUSTOMER("CU"),
	CONTAINER("CNT"),
	CREDIT_MEMO("CM"),
    CLEAR_RECEIPT("CRP"),
    CLOSING_ENTRY("CE"),
    CLEAR_PAYMENT("CPY"),
    CROSS_DEPOSIT("XDP"),
    CUSTOMER_GROUP("CG"),
    CASH_TYPE_MASTER("CPM"),
    COST_TYPE_MASTER("CTM"),
    COLLECTING_ORDER("CLD"),
    CASH_TRANSACTION_INCOME("CTI"),
    CASH_TRANSACTION_EXPENSE("CTE"),
    CONSIGNMENT_ORDER("CDR"),
    CASH_BANK_EXPENSE("CBE"),
    CASH_BANK_INCOME("CBI"),
    CASH_RESPONSIBILITY("CAR"),
    CLEAR_REIMBURSEMENT("CRS"),
    CLEAR_RECEIPT_RETAIL("CRE"),
    CANCELLATION_RECEIPT("CNR"),
    CANCELLATION_PAYMENT("CNP"),
    CONSIGNMENT_ORDER_PLAN("CDP"),
    CALCULATOR_MASTER_COST("CMC"),
    CALCULATOR_MASTER_PACK("CMP"),
    CREDIT_MEMO_SALES_PROMO("CMS"),
    CONSIGNMENT_SALES_ORDER("CSO"),
    CONSIGNMENT_ORDER_REVERSE("COR"),
    COLLECTING_ORDER_MASTER_COST("COM"),
    CREDIT_MEMO_EXPEDITION_SUBSIDY("CMR"),
    COLLECTING_ORDER_COST_COMPONENT("COC"),
    
    //D
    DUNNING("DU"),
    DEBIT_MEMO("DM"),
    DEAL_ORDER("DLO"),
    DELIVERY_ORDER("DO"),
    DELIVERY_PLANNING("DP"),
    DELIVERY_ROUTE_LK("LK"),
    DELIVERY_ROUTE_DK("DK"),
    DEBIT_MEMO_MANUAL("DMM"),
    DIRECT_SALES_ORDER("DSO"),
    DIRECT_SALES_RETURN("DSR"),
    DELIVERY_ORDER_GROUP("INV"),
    DIRECT_PURCHASE_ORDER("DPO"),
    DELIVERY_ORDER_REALIZATION("DOR"),
    DIRECT_INVOICE_VERIFICATION("DIV"),
    DO_REALIZATION_COST_COMPONENT("DCC"),
    DO_REALIZATION_COST_COMPONENT_GROUP("DCG"),

    //E
    EXPEDITION("EXP"),
    EXT1_PURCHASE_ORDER("EXP"),
    EXPEDITION_ORDER_LETTER("SJE"),
    EXT1_DIRECT_SALES_ORDER("BOGR"),
    
    //F
    FIX_COGS("FCG"),
    FIXED_ASSET("FA"),
    FIXED_ASSET_CATEGORY("FC"),
    FIXED_ASSET_FROM_PROCUREMENT("FP"),
    FUND_APPLICATION("PD"),
  
    //G
    GOODS_ISSUE("GI"),
    GENERAL_COST("GC"),
    GOODS_RECEIPT("GR"),
    GROUP_MEMBERSHIP("GMR"),
    GR_COST_COMPONENT("GRC"),
    GOODS_ISSUE_MANUAL("GIM"),
    GOODS_ISSUE_SEQUENCE("GI"),
    GOODS_RECEIPT_MANUAL("GRM"),
    GAS_PURCHASE_ORDER_REALIZATION("GPR"),
    GOODS_RECEIPT_ITEM_REGISTRATION("GRIR"),

    //I
    ITEM_REQUEST("IR"),
    INTER_JOURNAL("IJE"),
    INVENTORY_ITEM("IVT"),
    ITEM_CONVERSION("ICV"),
    ITEM_REGISTRATION("IRG"),
    INFORMATION_LETTER("IL"), 
    INVOICE_VERIFICATION("VO"),
    INTER_TRANSACTION_AP("IAP"),
    INTER_FACILITY_PAYMENT("IFC"),
    INVOICE_VERIFICATION_REFERENCE("VI"),
    INTER_TRANSACTION_REQUISITIONER("ITR"),
    INTER_FACILITY_PAYMENT_CLEARING("IFC"),
    INTER_TRANSACTION_ACKNOWLEDGEMENT("ITA"),

    //J
    JOURNAL_ENTRY("JE"),
    JOURNAL_BATCHING("JB"),

    //L
    LEND_ITEM("LIT"),
    LEND_ITEM_RETURN("LIR"),
    LOAN_REQUISITION("LRQ"),
    LOAN_ACKNOWLEDGEMENT("LDG"),

    //M
    MODULE("MD", 2),
    MOVING("MOV"),
    MACHINE("MCN"),
    MANUAL_BILLING("MIN"),
    MEMO_CONVERSION("MCV"),
    MASTER_ATTRIBUTE("MAT"),
    MANUFACTURE_REQUEST("MFQ"),
    MOVING_CONTAINER_ISSUE("MCI"),
    MANUFACTURE_REALIZATION("MFR"),
    MANUFACTURE_DISTRIBUTION("MFD"),
    MOVING_CONTAINER_RECEIPT("MCR"),
    MOVING_CONTAINER_DUMP_ITEM("MVD"),
    MANUAL_INVOICE_VERIFICATION("MVO"),
    MOVING_CONTAINER_TRANSFER_ORDER("MTO"),
    MOVING_CONTAINER_ISSUE_SEQUENCE("MCI"),
    MAKLOON_AND_STEAM_DISTRIBUTION("MSD"),
    MAKLOON_AND_STEAM_REALIZATION("MSR"),
    MAKLOON_AND_STEAM("MST"),
    
    //N
    NATURAL_GAS_SALES_ORDER("NSO"),
    
    //P
    PARTY("PTY"),
    PRODUCT("PRD"),
    PRODUCT_COLOUR("PC"),
    PAYMENT("PY"),
    PACKING("PG"),
    PROJECT("PRJ"),
    PAYROLL("THP"),
    PROSPECT("PC"),
    PRE_PAYMENT("RPR"),
    PICKING_ORDER("PK"),
    PRODUCT_BRAND("PBR"),
    PO_FROM_SALES("PFS"),
    PAYMENT_MANUAL("PYM"),
    PURCHASE_ORDER("PO"),
    PRODUCT_CATALOG("PRG"),
    PURCHASE_RETURN("PRN"),
    PRODUCTION_ORDER("WO"),
    PURCHASE_REQUEST("PR"),
    PAYROLL_OVERTIME("THO"),
    PRODUCT_CATEGORY("PRC"),
    PACK_TO_CONTAINER("PTC"),
    PO_COST_COMPONENT("PCC"),
    PURCHASE_DISCOUNT("PDN"),
    PURCHASE_SELECTION("PS"),
    PRODUCT_CONVERSION("PCV"),
    PAYABLE_PREPAYMENT("PPR"),
    PRE_TRANSFER_ORDER("PTO"),
    PAYMENT_MANUAL_TYPE("PMT"),
    PRICE_CATEGORY_TYPE("PCT"),
    PRODUCT_CONSUMPTION("PCS"),
    PRODUCTION_PLANNING("PPL"),
    PRODUCT_CHANGE_PRICE("PCP"), 
    PRE_STOCK_ADJUSTMENT("PSA"),
    PURCHASE_MASTER_COST("PMC"),
    PURCHASE_REQUISITION("PRQ"),
    PURCHASE_RETURN_MANUAL("PNM"),
    PURCHASE_ORDER_SERVICE("POS"),
    PROJECT_COST_COMPONENT("PJC"),
    PICKING_ORDER_ADJUSTMENT("OJ"),
    PRODUCT_CONVERSION_MEMO("PCM"),  
    PRE_STANDARD_SALES_ORDER("PSO"),
    PRE_STANDARD_SALES_ORDER_CUSTOMER("CSO"),
    PURCHASE_ORDER_CONFIRMAION("POC"),
    PRODUCTION_MATERIAL_REQUEST("PMR"),
    PRODUCT_CONVERSION_TRANSFER("PVT"),  
    PRODUCTION_ORDER_REALIZATION("POR"),
    PO_COST_COMPONENT_VERIFICATION("PVO"),
    PURCHASE_RETURN_MEMO_CONVERSION("PRM"),
    PAYABLES_CONTRA_BON_DOCUMENT("RKP"),
    PURCHASE_ORDER_FROM_BARCODE("POB"),
    PURCHASE_RETURN_FROM_BARCODE("PRB"),
    PERSON_APPROVER("PA"),

    //O
    OUTGOING_PREPAYMENT("OP"),
    
    //R
    RECEIPT("RP"),
    RETAIL_BILLING("RB"),
    REIMBURSEMENT("RMR"),
    RECEIPT_RETAIL("RE"),
    RECEIPT_MANUAL("RPM"),
    RETAIL_SALES_ORDER("RSO"),
    RECURRING_PURCHASE("RCP"),
    REIMBURSEMENT_CASH("RMC"),
    REIMBURSEMENT_BANK("RMB"),
    RECEIPT_MANUAL_TYPE("RMT"),
    RETAIL_SALES_RETURN("SRR"),
    REIMBURSEMENT_MASTER("RMS"),
    REQUEST_FOR_QUOTATION("RQ"),
    RECEIVABLES_DEDUCTION("RDD", 1),
    RECEIVABLES_CONTRA_BON("RKP", 1),
    RECURRING_JOURNAL_ENTRY("RJE"),
    REIMBURSEMENT_REQUISITION("RMQ"),
    
    //S
    SUPPLIER("SU"),
    SHIPMENT("SHP"),
    SPBU_SHIFT("SFT"),
    SALES_CLAIM("SC"),
    SALES_PROMO("SPR"),
    SPBU_RECEIPT("SRT"),
    STOCK_OPNAME("SM"),
    SALES_RETURN("SRN"),
    SAMPLE_LETTER("SL"),
    SALES_DISCOUNT("SD"),
    SCRAP_ORDER_IN("SCI"),
    SCRAP_ORDER_OUT("SCO"),
    SALES_ESTIMATION("EST"),
    SALES_COMMISSION("SCN"),
    STOCK_ADJUSTMENT("SA"),
    SHIFT_MANAGEMENT("SHF"),
    SALES_MASTER_COST("SMC"),
    SALES_DISTRIBUTION("SD"),
    SALES_RETURN_MANUAL("SRM"),
    SALES_PROMO_CLEARING("SPC"),
    SHIPMENT_TYPE_MASTER("SPM"),
    STANDARD_SALES_ORDER("SSO"),
    SALES_ORDER_ADJUSTMENT("AJ"),
    SALES_ESTIMATION_GROUP("ESG"),
    STANDARD_PURCHASE_ORDER("SPO"),
    STANDARD_GAS_SALES_ORDER("GSO"),
    SO_COST_COMPONENT_VERIFICATION("SVO"),
    STOCK_ADJUSTMENT_RESPONSIBILITY("SAR"),
    STOCK_DEPRECIATION("SDP"),
    SALES_ORDER("SO"),
    
    //T
    TAX("TAX"),
    TRANSFER_CODE("TC"),
    TRANSFER_ORDER("TO"),
    TRANSPORT_EXPENSE("TRE"),
    TRANSFER_ORDER_MANUAL("TOM"),
    TRANSFER_ORDER_CONVERSION("TOC"),
    TRANSPORT_COST_MASTER("TRM"),
    TRANSFER_ORDER_BY_PASS("TOP"),
    TRANSFER_ORDER_REQUEST("TOR"),
    TRANSFER_ORDER_LOADING("TLO"),
    TRANSFER_ORDER_EXTERNAL("TOX"),
    TRANSPORT_EXPENSE_TEMPLATE("TRT"),
    TRANSPORT_OUTSOURCE_CONTRACT("TRC"),
    TRANSPORT_EXPENSE_REALIZATION("TRR"), 

    //Q
    QUOTATION_LETTER("QL"),
   
    //V
    VEHICLE("VHC"),
    VERIFICATION_MEMO("VM"),
    VEHICLE_MAINTENANCE("VHM"),
	
	//W
	WAREHOUSE_CASH("WHC");
	
	private String code;
	private Integer length = 5;
	
	private TableType(String code) {
		this.code = code;
	}
	
	private TableType(String code, Integer length) {
		this.code = code;
		this.length = length;
	}
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getLength() {
		return length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}
}
